import { locations } from './data/locations.js';
import { getState, setState } from './state/store.js';
import { getPrices } from './services/price-service.js';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let priceData={cokeZero:[],pepsiMax:[]},priceMeta={source:'loading',updatedAt:null},loadToken=0;
const volumeOf=pack=>{const m=pack.match(/(?:(\d+)\s*×\s*)?([\d,.]+)\s*L/i);return m?Number(m[1]||1)*Number(m[2].replace(',','.')):1.5};
const money=(n,c)=>new Intl.NumberFormat(c==='SEK'?'sv-SE':'nb-NO',{minimumFractionDigits:n%1?2:0,maximumFractionDigits:2}).format(n);
function showToast(title,sub=''){const t=$('#toast');t.innerHTML=`<strong>${title}</strong>${sub?`<small>${sub}</small>`:''}`;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2500)}
function statusText(){if(priceMeta.source==='loading')return'Oppdaterer priser…';if(priceMeta.source==='preview')return'Forhåndsvisningsdata · lokal prisinnhenting kommer';if(priceMeta.source==='fallback')return'Midlertidige reservepriser';const d=priceMeta.updatedAt?new Date(priceMeta.updatedAt):null;return d&&!Number.isNaN(+d)?`Prisdata oppdatert ${d.toLocaleString('nb-NO',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}`:'Prisdata hentet automatisk'}
function render(){const state=getState(),loc=locations[state.location]||locations.sandefjord;$('#locationLabel').textContent=loc.name;$('#dataStatus').textContent=statusText();$('#dataStatus').dataset.source=priceMeta.source;$$('#locationMenu [data-location]').forEach(b=>b.classList.toggle('active',b.dataset.location===state.location));$$('.card').forEach(card=>{const product=card.dataset.product;card.hidden=state.productFilter!=='all'&&state.productFilter!==product;card.querySelector('.heart-btn')?.classList.toggle('active',state.favorites.includes(product));let rows=(priceData[product]||[]).map(x=>({store:x[0],pack:x[1],price:x[2],offer:x[3],member:x[4],ppl:x[2]/volumeOf(x[1])}));if(state.offerOnly)rows=rows.filter(x=>x.offer);if(state.memberOnly)rows=rows.filter(x=>x.member);rows.sort(state.sort==='total'?(a,b)=>a.price-b.price:state.sort==='store'?(a,b)=>a.store.localeCompare(b.store):(a,b)=>a.ppl-b.ppl);card.querySelector('.price-list').innerHTML=rows.length?rows.map(x=>`<div class="price-row"><div class="store-logo">${x.store}</div><div class="price-meta">${x.pack}<small>${money(x.ppl,loc.currency)} ${loc.currency}/L${x.member?' · MEDLEMSPRIS':x.offer?' · TILBUD':''}</small></div><div class="amount ${x.offer||x.member?'offer':''}">${money(x.price,loc.currency)} <small>${loc.currency}</small></div></div>`).join(''):'<div class="empty-state">Ingen priser matcher filtrene.</div>'});$('#favoriteCount').textContent=state.favorites.length?` ${state.favorites.length}`:''}
async function loadPrices(){const token=++loadToken,location=getState().location;priceMeta={source:'loading',updatedAt:null};priceData={cokeZero:[],pepsiMax:[]};render();const result=await getPrices(location);if(token!==loadToken)return;priceData=result.data;priceMeta={source:result.source,updatedAt:result.updatedAt};render()}
$('#locationButton').addEventListener('click',()=>$('#locationMenu').classList.toggle('open'));$('#locationMenu').addEventListener('click',e=>{const b=e.target.closest('[data-location]');if(!b)return;setState({location:b.dataset.location});$('#locationMenu').classList.remove('open');loadPrices()});document.addEventListener('click',e=>{if(!e.target.closest('.location-wrap'))$('#locationMenu').classList.remove('open')});
function wireModal(id,openSel,closeSel){const m=$(id);$$(openSel).forEach(b=>b.addEventListener('click',()=>{m.classList.add('open');document.body.style.overflow='hidden';m.querySelector('button,input,select,textarea')?.focus()}));$$(closeSel).forEach(b=>b.addEventListener('click',()=>{m.classList.remove('open');document.body.style.overflow=''}));m.addEventListener('click',e=>{if(e.target===m){m.classList.remove('open');document.body.style.overflow=''}});return m}
const about=wireModal('#aboutModal','[data-about]','[data-close-about]'),tips=wireModal('#tipsModal','[data-tips]','[data-close-tips]');document.addEventListener('keydown',e=>{if(e.key==='Escape'){about.classList.remove('open');tips.classList.remove('open');document.body.style.overflow=''}});
let nectarClicks=0;$('#nectarEgg').addEventListener('click',()=>{if(++nectarClicks<5)return;nectarClicks=0;showToast('Du er åpenbart en av oss.','Jakten fortsetter.')});
$$('.tab').forEach(b=>b.addEventListener('click',()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');setState({productFilter:b.dataset.product});render()}));$('#offerOnly').addEventListener('change',e=>{setState({offerOnly:e.target.checked});render()});$('#memberOnly').addEventListener('change',e=>{setState({memberOnly:e.target.checked});render()});$('#sortMode').addEventListener('change',e=>{setState({sort:e.target.value});render()});
$('#priceCards').addEventListener('click',e=>{const b=e.target.closest('.heart-btn');if(!b)return;const fav=new Set(getState().favorites);fav.has(b.dataset.product)?fav.delete(b.dataset.product):fav.add(b.dataset.product);const arr=[...fav];localStorage.setItem('sorteGullFavs',JSON.stringify(arr));setState({favorites:arr});showToast(fav.has(b.dataset.product)?'Lagt til i favoritter.':'Fjernet fra favoritter.');render()});
$('#tipsForm').addEventListener('submit',e=>{e.preventDefault();tips.classList.remove('open');document.body.style.overflow='';e.target.reset();showToast('Takk for pristipset!','Vi tar det med videre i jakten.')});loadPrices();