const LOC={sandefjord:'Sandefjord',horten:'Horten',tromso:'Tromsø',stavanger:'Stavanger'};
const LOCAL={sandefjord:['KIWI','COOP_EXTRA','COOP_OBS','REMA_1000','MENY_NO','SPAR_NO'],horten:['KIWI','COOP_EXTRA','REMA_1000','MENY_NO'],tromso:['KIWI','COOP_EXTRA','COOP_OBS','REMA_1000','EUROSPAR','SPAR_NO'],stavanger:['KIWI','COOP_EXTRA','COOP_OBS','REMA_1000','MENY_NO','SPAR_NO']};
const NAME={KIWI:'KIWI',COOP_EXTRA:'Extra',COOP_OBS:'Obs',COOP_MEGA:'Coop Mega',COOP_PRIX:'Coop Prix',COOP_MARKED:'Coop Marked',REMA_1000:'REMA 1000',MENY_NO:'MENY',SPAR_NO:'SPAR',EUROSPAR:'EUROSPAR',BUNNPRIS:'Bunnpris',JOKER_NO:'Joker',EUROPRIS_NO:'Europris'};
const WANTED_PACKS=new Set([4,6,8,12,24]);
const productName=n=>{n=String(n||'').toLowerCase();if(n.includes('pepsi')&&n.includes('max'))return'Pepsi Max';const coke=n.includes('coca')||n.includes('coke');const zero=n.includes('zero')||n.includes('uten sukker')||n.includes('u/sukker')||n.includes('u. sukker')||n.includes('uten tilsatt sukker')||n.includes('sukkerfri');return coke&&zero?'Coca-Cola Zero':null};
function pkg(n='',w,u=''){const raw=String(n||'').toLowerCase().replace(/,/g,'.');let count=1,z=null,m;
m=raw.match(/(\d{1,2})\s*(?:stk|pk|pakk|pack|bx)?\s*[x×]\s*(\d+(?:\.\d+)?)\s*(ml|l)\b/);if(m){count=+m[1];z=+m[2]*(m[3]==='ml'?.001:1)}
if(!z&&(m=raw.match(/(\d+(?:\.\d+)?)\s*(ml|l)\s*[x×]\s*(\d{1,2})\b/))){z=+m[1]*(m[2]==='ml'?.001:1);count=+m[3]}
if(count===1&&(m=raw.match(/(\d{1,2})\s*(?:stk|pk|pakk|pack|bx)\b/)))count=+m[1];
if(!z&&(m=raw.match(/(\d+(?:\.\d+)?)\s*l\b/)))z=+m[1];
if(!z&&(m=raw.match(/(\d{2,4})\s*ml\b/)))z=+m[1]/1000;
const unit=String(u||'').toLowerCase(),weight=Number(w);if((!z||z>2)&&Number.isFinite(weight)){const total=unit==='ml'?weight/1000:unit==='l'?weight:null;if(total){if(count>1)z=total/count;else if(total<=2)z=total}}
if(!z||z<.2||z>2)return null;const sizeKey=Math.abs(z-.33)<.035?'033':Math.abs(z-.5)<.035?'05':Math.abs(z-1.5)<.08?'15':'other';const unitLabel=sizeKey==='033'?'0,33 L':sizeKey==='05'?'0,5 L':sizeKey==='15'?'1,5 L':String(Math.round(z*100)/100).replace('.',',')+' L';return{sizeKey,unitLiters:z,liters:z*count,count,pack:count>1?`${count} × ${unitLabel}`:unitLabel}}
async function req(path,h,opt={}){const r=await fetch('https://kassal.app/api/v1'+path,{...opt,headers:{...h,...opt.headers}});if(!r.ok){let d='';try{d=await r.text()}catch{}throw Error(`Kassalapp ${r.status}${d?' · '+d.slice(0,300):''}`)}return r.json()}
async function productSearch(q,h){try{const r=await req(`/products?search=${encodeURIComponent(q)}&size=100&unique=0&exclude_without_ean=1&sort=date_desc`,h);return r.data||[]}catch{return[]}}
const latestPriceDate=p=>{const hist=(p.price_history||[]).map(x=>x.date).filter(Boolean).map(x=>new Date(x).getTime()).filter(Number.isFinite);if(hist.length)return new Date(Math.max(...hist)).toISOString();return p.updated_at||p.created_at||null};
const fresh=d=>{if(!d)return false;const t=new Date(d).getTime();return Number.isFinite(t)&&(Date.now()-t)/86400000<=3};
async function load(location){const key=process.env.KASSALAPP_API_KEY;if(!key)throw Error('API-nøkkel mangler');const h={Authorization:`Bearer ${key}`,Accept:'application/json','Content-Type':'application/json','User-Agent':'JaktenPaDetSorteGull/2.1'};
const physical=await req(`/physical-stores?search=${encodeURIComponent(LOC[location])}&size=100`,h);const discovered=new Set((physical.data||[]).map(x=>x.group).filter(Boolean));const expected=[...new Set([...(LOCAL[location]||[]),...[...discovered].filter(c=>NAME[c])])];const allowed=new Set(expected);
const searches=await Promise.all(['Pepsi Max','Coca Cola Zero','Coca Cola uten sukker','Coca Cola 4'].map(q=>productSearch(q,h)));
const candidates=new Map(),rows=[];
for(const p of searches.flat()){const product=productName(p.name),info=pkg(p.name,p.weight,p.weight_unit),ean=String(p.ean||'');if(!product||!info||!ean)continue;if(!candidates.has(ean))candidates.set(ean,{ean,product,...info});const c=String(p.store?.code||'').toUpperCase(),price=Number(typeof p.current_price==='object'?p.current_price?.price:p.current_price),checked=latestPriceDate(p);if(allowed.has(c)&&Number.isFinite(price)&&fresh(checked))rows.push({ean,product,...info,chain:NAME[c]||p.store?.name||c,chainCode:c,price,lastChecked:checked,kind:'regular'})}
const ordered=[...candidates.values()].sort((a,b)=>{const pa=WANTED_PACKS.has(a.count)?0:a.sizeKey!=='other'?1:2,pb=WANTED_PACKS.has(b.count)?0:b.sizeKey!=='other'?1:2;return pa-pb}),selected=ordered.slice(0,100),eans=selected.map(x=>x.ean),selectedMap=new Map(selected.map(x=>[x.ean,x]));
if(eans.length){const bulk=await req('/products/prices-bulk',h,{method:'POST',body:JSON.stringify({eans,days:3,aggregation:'min'})});for(const item of bulk.data||[]){const base=selectedMap.get(String(item.ean));if(!base)continue;for(const st of item.stores||[]){const c=String(st.store||'').toUpperCase(),price=Number(st.current_price),checked=st.last_checked||null;if(!allowed.has(c)||!Number.isFinite(price)||!fresh(checked))continue;rows.push({...base,chain:NAME[c]||st.name||c,chainCode:c,price,lastChecked:checked,kind:'regular'})}}
const consolidated=new Map();for(const x of rows){const k=`${x.product}|${x.chainCode}|${x.pack}`;const prev=consolidated.get(k);if(!prev||x.price<prev.price)consolidated.set(k,x)}const clean=[...consolidated.values()];const chains=[...new Set(clean.map(x=>x.chain))].map(chain=>({chain,products:clean.filter(x=>x.chain===chain)}));
return{updatedAt:new Date().toISOString(),source:'Kassalapp API · ferske kjedepriser',location,coverage:{expected,returned:[...new Set(clean.map(x=>x.chainCode))],missing:expected.filter(c=>!clean.some(x=>x.chainCode===c)),eanCount:eans.length,catalog:{cokeMultipacks:ordered.filter(x=>x.product==='Coca-Cola Zero'&&WANTED_PACKS.has(x.count)).map(x=>({ean:x.ean,pack:x.pack})),pepsiMultipacks:ordered.filter(x=>x.product==='Pepsi Max'&&WANTED_PACKS.has(x.count)).map(x=>({ean:x.ean,pack:x.pack}))}},chains}}
export default async function handler(req,res){res.setHeader('Cache-Control','s-maxage=300, stale-while-revalidate=900');const location=String(req.query?.location||'sandefjord').toLowerCase();if(location==='stromstad')return res.status(200).json({source:'unavailable',location,chains:[],note:'Svenske priser er ikke koblet til en verifisert datakilde ennå.'});if(!LOC[location])return res.status(400).json({error:'Ukjent lokasjon'});try{return res.status(200).json(await load(location))}catch(e){return res.status(502).json({error:'Prisinnhenting feilet',detail:e.message})}}